# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38309d56441029c4a69506207a01aa10"
application_url = "https://ourselves-circle-cards-mp.trycloudflare.com"
embedded = true
name = "checkout-validation-app"
handle = "checkout-validation-app-17"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ourselves-circle-cards-mp.trycloudflare.com/auth/callback",
  "https://ourselves-circle-cards-mp.trycloudflare.com/auth/shopify/callback",
  "https://ourselves-circle-cards-mp.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
